/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOOKUP_GRADE_H_RPCGEN
#define _LOOKUP_GRADE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LOOKUPGRADE_PROG 0x20481025
#define LOOKUPGRADE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOOKUPGRADE 1
extern  char * lookupgrade_1(int *, CLIENT *);
extern  char * lookupgrade_1_svc(int *, struct svc_req *);
extern int lookupgrade_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOOKUPGRADE 1
extern  char * lookupgrade_1();
extern  char * lookupgrade_1_svc();
extern int lookupgrade_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOOKUP_GRADE_H_RPCGEN */
