/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "lookup_grade.h"

char *
lookupgrade_1_svc(int *argp, struct svc_req *rqstp)
{
	static char  result;
    
    result = lookUpGrade(*argp);
	/*
	 * insert server code here
	 */

	return &result;
}
