/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "post_update.h"


int
postupdate_prog_1(char *host, StudentSt* student_list)
{
	//printf("now in postupdate_prog_1\n");
    CLIENT *clnt;
	int  *result_1;
	StudentSt  postupdate_1_arg;



#ifndef	DEBUG
	clnt = clnt_create (host, POSTUPDATE_PROG, POSTUPDATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
        printf("post update call failed\n");
		return 0;//fail
	}
#endif	/* DEBUG */

	result_1 = postupdate_1(student_list, clnt);
    //printf("after postupdate_1()  \n");
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
        printf("post update call failed\n");
        return 0;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
    return 1;

}

/*
int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	postupdate_prog_1 (host);
    exit (0);
}*/

int post_update(char* host, StudentSt *student_list) {
    return postupdate_prog_1(host, student_list);
}
