/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UPDATE_GRADE_H_RPCGEN
#define _UPDATE_GRADE_H_RPCGEN

#include <rpc/rpc.h>
#include "../utils/student_grade_manage.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
struct StudentSt {
	int student_id;
	char grade;
	struct StudentSt *next;
};*/
typedef struct StudentSt StudentSt;

#define UPDATEGRADE_PROG 0x20481026
#define UPDATEGRADE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define UPDATEGRADE 1
extern  char * updategrade_1(StudentSt *, CLIENT *);
extern  char * updategrade_1_svc(StudentSt *, struct svc_req *);
extern int updategrade_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define UPDATEGRADE 1
extern  char * updategrade_1();
extern  char * updategrade_1_svc();
extern int updategrade_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_StudentSt (XDR *, StudentSt*);

#else /* K&R C */
extern bool_t xdr_StudentSt ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UPDATE_GRADE_H_RPCGEN */
